config/routes.rb
Amzday::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:create, :destroy]
  root :to => "static_pages#index"

  match '/register', to: 'users#new',         via: 'get'
  match '/login',    to: 'sessions#new',      via: 'get'
  match '/logout',   to: 'sessions#destroy',  via: 'delete'

  
  match '/help',    to: 'static_pages#help',     via: 'get'
  match '/about',   to: 'static_pages#about',    via: 'get'
  match '/contact', to: 'static_pages#contact',  via: 'get'

  

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	default_scope -> { order('created_at DESC') }
	validates :content, presence: true, length: { maximum: 500 }
	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  
  extend FriendlyId
  friendly_id :name, use: :slugged

	before_save { self.email = email.downcase }
	before_create :create_remember_token
	validates :name, presence: true, length: { maximum: 50 }
	validates :email, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },

                   uniqueness: { case_sensitive: false }

    validates :password, length: { minimum: 6 }

    has_secure_password
      
      def feed
        # This is preliminary. See "Following users" for the full implementation.
        Post.where("user_id = ?", id)
      end

      def User.new_remember_token
    	SecureRandom.urlsafe_base64
  	  end

      def User.encrypt(token)
    	Digest::SHA1.hexdigest(token.to_s)
      end  

      private

	  def create_remember_token
	    # Create the token.
      self.remember_token = User.encrypt(User.new_remember_token)
	  end      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Post created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/index'
    end
  end

  def destroy
     @post.destroy
     redirect_to root_url
  end

  private

    def post_params
      params.require(:post).permit(:content)
    end


    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_url if @post.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
  		if user && user.authenticate(params[:session][:password])
  			
    	# Sign the user in and redirect to the user's show page.
	    	log_in user
	    	redirect_back_or user
    	else
    		# Create an error message and re-render the signin form.
    		flash.now[:error] = 'Invalid email/password combination' 
      		render 'new'
		end
	end

	def destroy
		log_out
		redirect_to root_url
		
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  	if signed_in?
	   @post = current_user.posts.build 
    @feed_items = current_user.feed.paginate(page: params[:page])
    end

  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 before_action :signed_in_user, only: [:index,:edit, :update]
 before_action :correct_user,   only: [:edit, :update]
 before_action :admin_user,     only: :destroy
 
  def show 
	   @user = User.friendly.find(params[:id])
      @posts = @user.posts.paginate(page: params[:page])
  end

  def destroy
    User.friendly.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  def new
    @user = User.new
  end

   def index
    @users = User.paginate(page: params[:page])
  end
  
  def create
  	@user = User.new(user_params) 

  	if @user.save
      log_in @user
  	  flash[:success] = "Welcome to the BETA of amzDAY"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.friendly.find(params[:id])
  end

  def update
    @user = User.friendly.find(params[:id])
    if @user.update_attributes(user_params)
      # Handle a successful update.
       flash[:success] = "Profile updated"
      log_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end


    

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
    
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
  
    # Before filters

   

     def correct_user
      @user = User.friendly.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
	def full_title(page_title)
		base_title = "amzBETA"
		if page_title.empty?
			base_title
		else 
			"#{base_title} | #{page_title}"
		end	
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	 def log_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end


   def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
  	@current_user = user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end


   def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

   def current_user?(user)
    user == current_user
  end

   def log_out
    self.current_user = nil
    cookies.delete(:remember_token)
    end

    def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://amzday.heroku.com/">amzBETA</a>
    by Ahmed Hassan
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://twitter.com/amzVIEW">Follow Us</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "amzBETA", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log Out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Log in", login_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <%= favicon_link_tag 'amz-20130827-favicon.ico' %>
	  <title><%= full_title(yield(:title)) %></title>
		  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		  <%= csrf_meta_tags %>
		  <%= render '/layouts/shim'%>
	</head>
	<body>
			<%= render '/layouts/header'%>
			
    		<div class="container">
    			<% flash.each do |key, value| %>
			        <div class="alert alert-<%= key %>"><%= value %></div>
			     <% end %>
				<%= yield %>
				<%= render '/layouts/footer'%>
				<%= debug(params) if Rails.env.development? %>
			</div>
	</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<li>
  <span class="content"><%= post.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
  </span>
  <% if current_user?(post.user) %>
    <%= link_to "delete", post, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: post.content %>
  <% end %>
</li>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.content %></td>
        <td><%= post.user_id %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="posts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_post_form.html.erb
<%= form_for(@post) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new post..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 52), current_user %>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.posts.count, "post") %>
</span>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us')%>
		<h1>About Us</h1>
			<p>
				
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ultrices erat nisl, id cursus magna elementum in. Praesent ac lacus nec turpis facilisis placerat in rhoncus velit. Proin eu feugiat metus. Nam in sem ornare quam tempor congue. Suspendisse quis mi ut felis tincidunt dapibus quis at lacus. Ut vel lacus iaculis, sollicitudin enim rhoncus, venenatis urna. Suspendisse dolor justo, molestie vel libero et, vestibulum malesuada arcu. Vestibulum venenatis, lorem id porta posuere, nisi massa cursus sapien, vitae mattis tortor ante eu ligula. Mauris a sollicitudin orci, quis venenatis nunc.

			</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us')%>
		<h1>Contact Us</h1>
			<p>
				
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ultrices erat nisl, id cursus magna elementum in. Praesent ac lacus nec turpis facilisis placerat in rhoncus velit. Proin eu feugiat metus. Nam in sem ornare quam tempor congue. Suspendisse quis mi ut felis tincidunt dapibus quis at lacus. Ut vel lacus iaculis, sollicitudin enim rhoncus, venenatis urna. Suspendisse dolor justo, molestie vel libero et, vestibulum malesuada arcu. Vestibulum venenatis, lorem id porta posuere, nisi massa cursus sapien, vitae mattis tortor ante eu ligula. Mauris a sollicitudin orci, quis venenatis nunc.

			</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help')%>
	<h1>Help</h1>
		<p>
				
		Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ultrices erat nisl, id cursus magna elementum in. Praesent ac lacus nec turpis facilisis placerat in rhoncus velit. Proin eu feugiat metus. Nam in sem ornare quam tempor congue. Suspendisse quis mi ut felis tincidunt dapibus quis at lacus. Ut vel lacus iaculis, sollicitudin enim rhoncus, venenatis urna. Suspendisse dolor justo, molestie vel libero et, vestibulum malesuada arcu. Vestibulum venenatis, lorem id porta posuere, nisi massa cursus sapien, vitae mattis tortor ante eu ligula. Mauris a sollicitudin orci, quis venenatis nunc.

		</p>

app/views/static_pages/index.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/post_form' %>
      </section>
    </aside>

    <div class="span8">
      <h3>Post Feed</h3>
      <%= render 'shared/feed' %>
    </div>

  </div>
<% else %>
  <div class="center hero-unit">
    <h1>amzBETA</h1>

    <h2>
      This is the BETA version.
    </h2>

    <%= link_to "Register", register_path,
                                class: "btn btn-large btn-primary" %>
  </div>

  
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 30 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Register') %>
<h1>Register</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="span4">
		<section>

			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
		</section>
	</aside>
	<div class="span8">
    <% if @user.posts.any? %>
      <h3>Posts (<%= @user.posts.count %>)</h3>
      <ol class="posts">
        <%= render @posts %>
      </ol>
      <%= will_paginate @posts %>
    <% end %>
  </div>

</div>